In [ ]:
from google.colab import drive
drive.mount('/drive')

Mounted at /drive

In [ ]:
import glob
import pandas as pd
import random

In [ ]:
!pip install transformers

In [ ]:
# Scan all dataset csv files
csv_files = glob.glob('../drive/MyDrive/Colab Notebooks/Estimates/dataset/*.{}'.format('csv'))

In [ ]:
# Merge all csv files into one csv
df_inp = pd.concat([pd.read_csv(file) for file in csv_files ], ignore_index=True)

# EDA

In [ ]:
print('Max', df_inp["storypoint"].max(axis=0, numeric_only=True))
print('Min', df_inp["storypoint"].min(axis=0, numeric_only=True))
print('Avg', df_inp["storypoint"].mean(axis=0, numeric_only=True))
print('90th percentile', df_inp["storypoint"].quantile(0.9))
print('75th percentile', df_inp["storypoint"].quantile(0.75))
print('50th percentile', df_inp["storypoint"].quantile(0.5))
print('25th percentile', df_inp["storypoint"].quantile(0.25))

Max 100
Min 1
Avg 6.216746021533051
90th percentile 13.0
75th percentile 8.0
50th percentile 4.0
25th percentile 2.0

# Feature Engineering

In [ ]:
df_inp.shape

(23313, 4)

In [ ]:
df_inp_filt = df_inp[df_inp['storypoint'] <= 28]

In [ ]:
df_inp_filt.shape

(22692, 4)

In [ ]:
df_inp_filt['storypoint'].value_counts()

5     4319
1     4225
3     3973
2     3406
8     3112
13     981
4      836
20     452
6      406
10     389
21     117
12      82
15      69
16      59
7       53
9       34
14      26
11      21
19      20
17      20
26      18
18      16
24      14
22      14
28      10
25       9
23       8
27       3
Name: storypoint, dtype: int64

In [ ]:
# jiraa

In [ ]:
df_jiraa = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/jiraa.csv')

In [ ]:
df_jiraa.shape

(87, 17)

In [ ]:
df_jiraa = df_jiraa[df_jiraa['Label'].notna()]

In [ ]:
df_jiraa.head(5)

,Task name,Task description,Label,Task priority,Sprint number,Planned estimate,Actual estimate,Optimistic,Most likely,Pessimistic,Risk factor,Weighted average,Standard deviation,Confidence interval,Complexity factor,Final esimate,Unnamed: 16
6,Tune the model training parameters to improve ...,Experiment with model hyperparameters by obser...,EST_AI,Medium,ET Sprint 4,12,12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Evaluate the model,Evaluate the trained model performance on the ...,EST_AI,Medium,ET Sprint 3,8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Train the model,Use a high computational system for training t...,EST_AI,Medium,ET Sprint 3,24,23,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Create training and utility scripts,Training script - Create a model training scri...,EST_AI,Medium,ET Sprint 3,8,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,"Create model architecture, Define loss functio...",Model architecture - Define the model branches...,EST_AI,Medium,ET Sprint 3,8,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_jiraa = df_jiraa.loc[~(df_jiraa['Planned estimate'] == 0)]

In [ ]:
df_jiraa.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/jira_final.csv')

In [ ]:
# Prepare dataset

In [ ]:
df_jiraa['Planned estimate'].value_counts()

8     31
16    24
12     6
2      5
4      4
20     3
56     3
24     2
32     2
3      2
5      1
35     1
14     1
6      1
1      1
Name: Planned estimate, dtype: int64

In [ ]:
df_inp_filt.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/data.csv')

In [ ]:
# Read the filtered data
df_input = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/data_final.csv')

In [ ]:
df_input.shape

(16551, 5)

In [ ]:
df_input.head(5)

,Unnamed: 0,issuekey,Task name,Task description,Planned estimate
0,0,TDQ-249,SQL Server Single Sign On Support doesn't work...,"In the data profiler perspective, you can't us...",6
1,1,TDQ-309,Remove two columns in frequency tables,"in the ""b01_column_basic.jrxml"" report, freque...",16
2,3,TDQ-2699,"multiple analysis indicators are ""grayed out"" ...","When attempting to analyze DB2 table columns, ...",6
3,4,TDQ-1816,"""View invalid rows"" menu does not display on a...","If the DQ Rule has a ""join condition"", it is i...",16
4,5,TDQ-2350,Hide MDM connection in the Data Explorer persp...,I have a MDM connection in my DQ repository an...,6

In [ ]:
df_input_sampled = df_input.sample(n=6000)

In [ ]:
df_input_sampled['Planned estimate'].value_counts()

2     1522
6     1459
4     1286
16    1057
8      304
20     158
12     132
24      36
14      25
32      16
56       5
Name: Planned estimate, dtype: int64

In [ ]:
df_input_sampled.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/filtered_data_internet.csv')

In [ ]:
#Combine data internet + jira

In [ ]:
df_jiraa = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/jira_final.csv')

In [ ]:
df_input_sampled.shape

(6000, 6)

In [ ]:
df_input_sampled = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/filtered_data_internet.csv')

In [ ]:
df_jiraa.shape

(87, 18)

In [ ]:
df_input_sampled = df_input_sampled.drop('Unnamed: 0', axis=1)

In [ ]:
df_input_sampled = df_input_sampled.drop('Unnamed: 0.1', axis=1)

In [ ]:
df_input_sampled = df_input_sampled.drop('issuekey', axis=1)

In [ ]:
df_input_sampled.head(2)

,Task_name,Task_description,Label,Task_priority,Sprint_number,Planned_estimate,Actual_estimate,Optimistic,Most_likely,Pessimistic
0,add task to meas_astrom to fit an aribtrary WC...,"Sometime in the past, Russell Owen wrote a met...",EST_BE,Medium,INT Sprint 1,4,4,3,4,5
1,"analysis run by right click, the summary secti...","open an analysis, and run it by right click --...",EST_BE,Medium,INT Sprint 1,6,6,5,6,6

In [ ]:
df_jiraa = df_jiraa.drop('Unnamed: 0', axis=1)
df_jiraa = df_jiraa.drop('Unnamed: 16', axis=1)

In [ ]:
df_jiraa.head (2)

,Task_name,Task_description,Label,Task_priority,Sprint_number,Planned_estimate,Actual_estimate,Optimistic,Most_likely,Pessimistic
0,Tune the model training parameters to improve ...,Experiment with model hyperparameters by obser...,EST_AI,Medium,ET Sprint 4,12,12,12,12,13
1,Evaluate the model,Evaluate the trained model performance on the ...,EST_AI,Medium,ET Sprint 3,8,9,8,8,10

In [ ]:
df_input_sampled.insert(2, "Label", "EST_BE")

In [ ]:
df_input_sampled.insert(3, "Task priority", "Medium")

In [ ]:
df_input_sampled.insert(4, "Sprint number", "INT Sprint 1")

In [ ]:
df_jiraa = df_jiraa.rename(columns={'Task name': 'Task_name', 'Task description': 'Task_description', 'Task priority': 'Task_priority', 'Sprint number': 'Sprint_number', 'Planned estimate': 'Planned_estimate', 'Actual estimate': 'Actual_estimate', 'Most likely': 'Most_likely', 'Risk factor': 'Risk_factor', 'Weighted average': 'Weighted_average', 'Standard deviation': 'Standard_deviation', 'Complexity factor': 'Complexity_factor', 'Confidence interval': 'Confidence_interval'})

In [ ]:
df_jiraa = df_jiraa.drop('Final esimate', axis=1)

In [ ]:
df_input_sampled = df_input_sampled.rename(columns={'Task name': 'Task_name', 'Task description': 'Task_description', 'Task priority': 'Task_priority', 'Planned estimate': 'Planned_estimate'})

In [ ]:
df_input_sampled = df_input_sampled.rename(columns={'Sprint number': 'Sprint_number'})

In [ ]:
import numpy as np

In [ ]:
df_input_sampled = df_input_sampled.assign(Actual_estimate = df_input_sampled.Planned_estimate + np.random.randint(0, 2, df_input_sampled.shape[0]))

In [ ]:
df_input_sampled = df_input_sampled.assign(Optimistic = df_input_sampled.Planned_estimate + np.random.randint(-1, 0, df_input_sampled.shape[0]))
df_input_sampled = df_input_sampled.assign(Most_likely = df_input_sampled.Planned_estimate + np.random.randint(0, 1, df_input_sampled.shape[0]))
df_input_sampled = df_input_sampled.assign(Pessimistic = df_input_sampled.Planned_estimate + np.random.randint(0, 2, df_input_sampled.shape[0]))

In [ ]:
df_jiraa = df_jiraa.drop('Optimistic', axis=1)
df_jiraa = df_jiraa.drop('Most_likely', axis=1)
df_jiraa = df_jiraa.drop('Pessimistic', axis=1)

In [ ]:
df_jiraa = df_jiraa.drop('Risk_factor', axis=1)
df_jiraa = df_jiraa.drop('Weighted_average', axis=1)
df_jiraa = df_jiraa.drop('Confidence_interval', axis=1)
df_jiraa = df_jiraa.drop('Standard_deviation', axis=1)
df_jiraa = df_jiraa.drop('Complexity_factor', axis=1)

In [ ]:
df_jiraa_copy = df_jiraa.copy(deep=True)

In [ ]:
df_jiraa_copy.shape

(87, 10)

In [ ]:
#df_jiraa = df_jiraa.assign(Optimistic = df_jiraa.Planned_estimate + np.random.randint(-1, 0, df_jiraa.shape[0]))
#df_jiraa = df_jiraa.assign(Most_likely = df_jiraa.Planned_estimate + np.random.randint(0, 1, df_jiraa.shape[0]))
#df_jiraa = df_jiraa.assign(Pessimistic = df_jiraa.Planned_estimate + np.random.randint(0, 2, df_jiraa.shape[0]))

In [ ]:
df_jiraa["Optimistic"] = df_jiraa["Planned_estimate"] + np.random.randint(0, 1, df_jiraa.shape[0])
df_jiraa["Most_likely"] = df_jiraa["Planned_estimate"] + np.random.randint(0, 2, df_jiraa.shape[0])
df_jiraa["Pessimistic"] = df_jiraa["Planned_estimate"] + np.random.randint(0, 3, df_jiraa.shape[0])

In [ ]:
####

In [ ]:
frames = [df_jiraa, df_jiraa, df_input_sampled, df_jiraa, df_jiraa, df_jiraa]

result = pd.concat(frames)

In [ ]:
result.shape

(6435, 10)

In [ ]:
result.head(3)

,Task_name,Task_description,Label,Task_priority,Sprint_number,Planned_estimate,Actual_estimate,Optimistic,Most_likely,Pessimistic
0,Tune the model training parameters to improve ...,Experiment with model hyperparameters by obser...,EST_AI,Medium,ET Sprint 4,12,12,12,12,13
1,Evaluate the model,Evaluate the trained model performance on the ...,EST_AI,Medium,ET Sprint 3,8,9,8,8,10
2,Train the model,Use a high computational system for training t...,EST_AI,Medium,ET Sprint 3,24,23,24,25,26

In [ ]:
result["Weighted_average"] = round(((result["Optimistic"] + (4*result["Most_likely"]) + result["Pessimistic"])/6), 2)
result["Standard_deviation"] = round(((result["Pessimistic"] - result["Optimistic"])/6), 2)
result["Risk_factor"] = round((result["Standard_deviation"]/result["Weighted_average"]), 2)
result["Standard_confidence"] = result["Weighted_average"]
result["High_confidence"] = round((result["Weighted_average"] + (0.53 * result["Standard_deviation"])), 2)
result["Higher_confidence"] = round((result["Weighted_average"] + (1.28 * result["Standard_deviation"])), 2)
result["Highest_confidence"] = round((result["Weighted_average"] + (2.33 * result["Standard_deviation"])), 2)
result["Final_estimate"] = round((result["Highest_confidence"]), 1)

In [ ]:
result["Variance"] = round(((6*result["Pessimistic"] - result["Optimistic"])**2), 2)

In [ ]:
result.head(3)

In [ ]:
result.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/input_data.csv')

In [ ]:
result["Final_estimate"] = result["Final_estimate"].astype(int)

In [ ]:
### creating model now
df_res = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/input_data.csv')

In [ ]:
df_res.shape

(6435, 20)

In [ ]:
df_res.head(2)

,Unnamed: 0,Task_name,Task_description,Task_label,Task_priority,Sprint_number,Planned_estimate,Actual_estimate,Optimistic,Most_likely,Pessimistic,Weighted_average,Standard_deviation,Risk_factor,Standard_confidence,High_confidence,Higher_confidence,Highest_confidence,Final_estimate,Variance
0,0,Tune the model training parameters to improve ...,Experiment with model hyperparameters by obser...,EST_AI,Medium,ET Sprint 4,12,12,12,12,13,12.17,0.17,0.01,12.17,12.26,12.39,12.57,12,4356
1,1,Evaluate the model,Evaluate the trained model performance on the ...,EST_AI,Medium,ET Sprint 3,8,9,8,8,10,8.33,0.33,0.04,8.33,8.50,8.75,9.10,8,2704

In [ ]:
df_res = df_res.rename(columns={'Label': 'Task_label'})

In [ ]:
df_res['Final_estimate'] = np.where((df_res['Risk_factor'] >= 0) & (df_res['Risk_factor'] <= 0.05), df_res['Standard_confidence'], df_res['Final_estimate'])
df_res['Final_estimate'] = np.where((df_res['Risk_factor'] > 0.05) & (df_res['Risk_factor'] <= 0.1), df_res['High_confidence'], df_res['Final_estimate'])
df_res['Final_estimate'] = np.where((df_res['Risk_factor'] > 0.1) & (df_res['Risk_factor'] <= 0.15), df_res['Higher_confidence'], df_res['Final_estimate'])

In [ ]:
df_res["Final_estimate"] = df_res["Final_estimate"].astype(int)

## **One Hot Encoding**

In [ ]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

Features

In [ ]:
#Task_label
tl_enc = OneHotEncoder(sparse=False)
tl_train = df_res["Task_label"].to_numpy().reshape(-1,1)
tl_enc.fit(tl_train)
len_tl_enc = tl_enc.categories_[0].shape
print(len_tl_enc)

In [ ]:
#Planned_estimate
pe_enc = OneHotEncoder(sparse=False)
pe_train = df_res["Planned_estimate"].to_numpy().reshape(-1,1)
pe_enc.fit(pe_train)
len_pe_enc = pe_enc.categories_[0].shape
print(len_pe_enc)

In [ ]:
#Final_estimate
fe_enc = OneHotEncoder(sparse=False)
fe_train = df_res["Final_estimate"].to_numpy().reshape(-1,1)
fe_enc.fit(fe_train)
len_fe_enc = fe_enc.categories_[0].shape
print(len_fe_enc)

Label

In [ ]:
#Actual_estimate
ae_enc = OneHotEncoder(sparse=False)
ae_train = df_res["Actual_estimate"].to_numpy().reshape(-1,1)
ae_enc.fit(ae_train)
len_ae_enc = ae_enc.categories_[0].shape
print(len_ae_enc)

## **Split Data**

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train_df_res, test_df_res = train_test_split(df_res, test_size=0.1, random_state=42, shuffle=True)

In [ ]:
test_df_res.shape

## **Gpt-2 tokenizer & pre-trained model**

In [ ]:
import tensorflow as tf
from transformers import GPT2Tokenizer, TFGPT2Model

In [ ]:
class GPT:
    def __init__(self):
        self.tokenizer = GPT2Tokenizer.from_pretrained('gpt2')
        self.model = TFGPT2Model.from_pretrained('gpt2')

    def inp_vector(self, inp):
        encoded_inp = self.tokenizer(inp, return_tensors='tf')
        out = self.model(encoded_inp)
        vector = out[0].numpy()[0]
        return np.mean(vector, axis=0)

    def vectors(self, inps):
        feat_vectors = []
        for i in inps:
            if type(i) != 'str':
                i = "NA"
            feat_vectors.append(self.inp_vector(i))
        return np.array(feat_vectors)

gpt_model = GPT()

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

All PyTorch model weights were used when initializing TFGPT2Model.

All the weights of TFGPT2Model were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFGPT2Model for predictions without further training.

## **Features Encoding**

Task Name

In [ ]:
# training embeddings
tn_train = gpt_model.vectors(train_df_res["Task_name"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_name_train.npy', tn_train)
print(type(tn_train))
print(tn_train.shape)

In [ ]:
# testing embeddings
tn_test = gpt_model.vectors(test_df_res["Task_name"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_name_test.npy', tn_test)
print(type(tn_test))
print(tn_test.shape)

<class 'numpy.ndarray'>
(644, 768)

Task description

In [ ]:
# training embeddings
td_train = gpt_model.vectors(train_df_res["Task_description"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_desc_train.npy', td_train)
print(type(td_train))
print(td_train.shape)

In [ ]:
# testing embeddings
td_test = gpt_model.vectors(test_df_res["Task_description"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_desc_test.npy', td_test)
print(type(td_test))
print(td_test.shape)

<class 'numpy.ndarray'>
(644, 768)

Task label

In [ ]:
# training embeddings
tl_train = gpt_model.vectors(train_df_res["Task_label"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_label_train.npy', tl_train)
print(type(tl_train))
print(tl_train.shape)

In [ ]:
# testing embeddings
tl_test = gpt_model.vectors(test_df_res["Task_label"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/task_label_test.npy', tl_test)
print(type(tl_test))
print(tl_test.shape)

<class 'numpy.ndarray'>
(5791, 768)

Planned estimate

In [ ]:
# training embeddings
pe_train = gpt_model.vectors(test_df_res["Planned_estimate"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/planned_est_train.npy', pe_train)
print(type(pe_train))
print(pe_train.shape)

In [ ]:
# testing embeddings
pe_test = gpt_model.vectors(test_df_res["Planned_estimate"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/planned_est_test.npy', pe_test)
print(type(pe_test))
print(pe_test.shape)

<class 'numpy.ndarray'>
(5791, 768)

Final estimate

In [ ]:
# training embeddings
fe_train = gpt_model.vectors(train_df_res["Final_estimate"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/final_est_train.npy', fe_train)
print(type(fe_train))
print(fe_train.shape)

In [ ]:
# testing embeddings
fe_test = gpt_model.vectors(test_df_res["Final_estimate"])
np.save('../drive/MyDrive/Colab Notebooks/Estimates/final_est_test.npy', fe_test)
print(type(fe_test))
print(fe_test.shape)

<class 'numpy.ndarray'>
(5791, 768)

## Load features

In [ ]:
# Load feature encodings - Task name, task description, task label, planned estimate & final estimate
tn_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_name_train.npy')
tn_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_name_test.npy')

td_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_desc_train.npy')
td_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_desc_test.npy')

tl_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_label_train.npy')
tl_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/task_label_test.npy')

pe_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/planned_est_train.npy')
pe_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/planned_est_test.npy')

fe_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/final_est_train.npy')
fe_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/final_est_test.npy')

## **Define NN Architecture**

In [ ]:
# Branch-1 Task name
inp1 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_1")
lay1 = tf.keras.layers.Dense(128, activation='relu')(inp1)
lay1 = tf.keras.layers.Dropout(0.2)(lay1)
lay1 = tf.keras.layers.Dense(128, activation='relu')(lay1)

# Branch-2 Task description
inp2 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_2")
lay2 = tf.keras.layers.Dense(512, activation='relu')(inp2)
lay2 = tf.keras.layers.Dense(128, activation='relu')(lay2)

# Branch-2 Task label
inp3 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_3")
lay3 = tf.keras.layers.Dense(512, activation='relu')(inp3)
lay3 = tf.keras.layers.Dense(128, activation='relu')(lay3)

# Branch-2 Planned estimate
inp4 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_4")
lay4 = tf.keras.layers.Dense(512, activation='relu')(inp4)
lay4 = tf.keras.layers.Dense(128, activation='relu')(lay4)

# Branch-5 Final estimate
inp5 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_5")
lay5 = tf.keras.layers.Dense(512, activation='relu')(inp5)
lay5 = tf.keras.layers.Dense(128, activation='relu')(lay5)

# Concatenate Branch
out = tf.keras.layers.Concatenate()([lay1, lay2, lay3, lay4, lay5])
out = tf.keras.layers.Dense(384, activation='relu')(out)
out = tf.keras.layers.Dense(128, activation='relu')(out)
out = tf.keras.layers.Dense(216, activation='softmax')(out)

model = tf.keras.models.Model(inputs=[inp1, inp2, inp3, inp4, inp5], outputs=out)

In [ ]:
model.compile(tf.keras.optimizers.Adam(learning_rate=1e-3), loss='categorical_crossentropy', metrics=['accuracy'])
model.summary()

In [ ]:
checkpoint = tf.keras.callbacks.ModelCheckpoint('model.h5', monitor='loss', save_best_only=True, verbose=1)

## **Model Training**

In [ ]:
train_sh = model.fit(
    [tn_train, td_train, tl_train, pe_train, fe_train], ae_train,
    epochs=100,
    callbacks=[checkpoint],
    validation_data=([tn_test, td_test, tl_test, pe_test, fe_test], ae_test),
    batch_size=32,
    verbose=1
)

In [ ]:
print(train_sh.history)
model.save('../drive/MyDrive/Colab Notebooks/Estimates/model1.h5')
results = model.evaluate([tn_test, td_test, tl_test, pe_test, fe_test], ae_test, batch_size=16)

predictions = model.predict([tn_test, td_test, tl_test, pe_test, fe_test])

print(predictions.shape)
print(test_ae.shape)

y_actual_label = test_df_res["Actual_estimate"]
y_pred_label = enc.inverse_transform(predictions)
print(y_actual_label.shape, y_pred_label.shape)

test_df_res['Ai_estimate'] = y_pred_label
test.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/Model1_results.csv')

test.head(3)

In [ ]:
#result.loc[result['Risk_factor'] <= 0.05, 'Final_estimate'] = result['Standard_confidence']
#result.loc[result['Risk_factor'] >= 0.06 & result['Risk_factor'] <= 0.1, 'Final_estimate'] = result['High_confidence']
#result.loc[result['Risk_factor'] >= 0.11 & result['Risk_factor'] <= 0.15, 'Final_estimate'] = result['Higher_confidence']
#result.loc[result['Risk_factor'] > 0.15, 'Final_estimate'] = result['Highest_confidence']

In [ ]:
# Prepare input dataset
df_inp.loc[df_inp["storypoint"] <= 2, 'Work Complexity'] = 'Low'
df_inp.loc[(df_inp["storypoint"] > 2) & (df_inp["storypoint"] < 8), 'Work Complexity'] = 'Medium'
df_inp.loc[df_inp["storypoint"] >= 8, 'Work Complexity'] = 'High'

In [ ]:
issuekeyid = ['TISTUD', 'APSTUD', 'BAM', 'CLOV', 'DM', 'DURACLOUD', 'JSW', 'MESOS', 'MDL', 'MULE', 'STUDIO', 'XD', 'TDQ', 'TESB', 'TIMOB', 'USERGRID']

In [ ]:
optest = []
for index, row in df_inp.iterrows():
  if 'MULE' or 'TISTUD' or 'APSTUD' or 'USERGRID' or 'JSW' or 'TDQ' in row['issuekey']:
    row["Optimistic Estimate"] = row['storypoint'] + round(random.uniform(1, 2))
  if 'BAM' or 'CLOV' or 'DURACLOUD' or 'MESOS' or 'TIMOB' in row['issuekey']:
    row["Optimistic Estimate"] = row['storypoint'] + round(random.uniform(2, 3))
  if 'DM' or 'MDL' or 'STUDIO' or 'XD' or 'TESB' in row['issuekey']:
    row["Optimistic Estimate"] = row['storypoint'] + round(random.uniform(3, 4))
  optest.append(row["Optimistic Estimate"])

df_inp["Optimistic Estimate"] = optest

In [ ]:
moslikest = []
pesest = []
for index, row in df_inp.iterrows():
  if row["storypoint"] > 6:
    row["Most Likely Estimate"] = round(row['Optimistic Estimate'] * round(random.uniform(1, 2), 1))
    row["Pessimistic Estimate"] = round(row['Optimistic Estimate'] * round(random.uniform(2, 3), 1))

  if row["storypoint"] <= 6:
    row["Most Likely Estimate"] = round(row['Optimistic Estimate'] * round(random.uniform(1, 2), 1))
    row["Pessimistic Estimate"] = row["Most Likely Estimate"]

  moslikest.append(row["Most Likely Estimate"])
  pesest.append(row["Pessimistic Estimate"])

df_inp["Most Likely Estimate"] = moslikest
df_inp["Pessimistic Estimate"] = pesest

In [ ]:
df_inp["Weighted Average"] = round(((df_inp["Optimistic Estimate"] + (4*df_inp["Most Likely Estimate"]) + df_inp["Pessimistic Estimate"])/6), 2)
df_inp["Standard Deviation"] = round(((df_inp["Pessimistic Estimate"] - df_inp["Optimistic Estimate"])/6), 2)
df_inp["Risk Factor"] = round((df_inp["Standard Deviation"]/df_inp["Weighted Average"]), 2)
df_inp["Standard Confidence"] = df_inp["Weighted Average"]
df_inp["High Confidence"] = round((df_inp["Weighted Average"] + (0.53 * df_inp["Standard Deviation"])), 2)
df_inp["Higher Confidence"] = round((df_inp["Weighted Average"] + (1.28 * df_inp["Standard Deviation"])), 2)
df_inp["Highest Confidence"] = round((df_inp["Weighted Average"] + (2.33 * df_inp["Standard Deviation"])), 2)

df_inp["Final Estimate"] = round(df_inp["Highest Confidence"])

In [ ]:
# Save the final csv. This will be our input dataset
df_inp.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/data.csv')

In [ ]:
df_inp.tail(5)

# Prepare dataset for Training

In [ ]:
# split the data into train and test set
train, test = train_test_split(df_inp, test_size=0.2, random_state=42, shuffle=True)

In [ ]:
type(train)

In [ ]:
train.shape

In [ ]:
test.shape

In [ ]:
train.head(10)

In [ ]:
test.head(10)

## GPT-2 Model & Tokenizer

# Feature Encoding

In [ ]:
issuekey_vec_train = gpt_model.vectors(train["issuekey"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/issuekey_vec_train.npy', issuekey_vec_train)

In [ ]:
type(issuekey_vec_train)

In [ ]:
issuekey_vec_train.shape

In [ ]:
issuekey_vec_test = gpt_model.vectors(test["issuekey"])

In [ ]:
type(issuekey_vec_test)

In [ ]:
issuekey_vec_test.shape

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/issuekey_vec_test.npy', issuekey_vec_test)

In [ ]:
title_vec_test = gpt_model.vectors(test["title"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/title_vec_test.npy', title_vec_test)

In [ ]:
type(title_vec_test)

In [ ]:
title_vec_test.shape

In [ ]:
train.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/train_data.csv')

In [ ]:
test.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/test_data.csv')

In [ ]:
title_vec_train = gpt_model.vectors(train["title"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/title_vec_train.npy', title_vec_train)

In [ ]:
description_vec_test = gpt_model.vectors(test["description"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/description_vec_test.npy', description_vec_test)

In [ ]:
description_vec_train = gpt_model.vectors(train["description"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/description_vec_train.npy', description_vec_train)

In [ ]:
# Load train & test datasets

In [ ]:
train = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/train_data.csv')
test = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/test_data.csv')

In [ ]:
train.shape

(18650, 17)

In [ ]:
test.shape

(4663, 17)

In [ ]:
# Calculating and saving embeddings fro work complexity, optimistic estimates and risk factor

In [ ]:
# Work Complexity

In [ ]:
work_comp_train = gpt_model.vectors(train["Work Complexity"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/work_comp_train.npy', work_comp_train)

In [ ]:
work_comp_test = gpt_model.vectors(test["Work Complexity"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/work_comp_test.npy', work_comp_test)

In [ ]:
work_comp_train.shape

In [ ]:
work_comp_test.shape

In [ ]:
# Optimistic Estimate

In [ ]:
opt_est_train = gpt_model.vectors(train["Optimistic Estimate"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/opt_est_train.npy', opt_est_train)

In [ ]:
opt_est_test = gpt_model.vectors(test["Optimistic Estimate"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/opt_est_test.npy', opt_est_test)

In [ ]:
opt_est_train.shape

In [ ]:
opt_est_test.shape

In [ ]:
# Risk Factor

In [ ]:
risk_fac_train = gpt_model.vectors(train["Risk Factor"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/risk_fac_train.npy', risk_fac_train)

In [ ]:
risk_fac_test = gpt_model.vectors(test["Risk Factor"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/risk_fac_test.npy', risk_fac_test)

In [ ]:
risk_fac_train.shape

In [ ]:
risk_fac_test.shape

In [ ]:
# High Confidence

In [ ]:
high_conf_train = gpt_model.vectors(train["High Confidence"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/high_conf_train.npy', high_conf_train)

In [ ]:
high_conf_test = gpt_model.vectors(test["High Confidence"])

In [ ]:
np.save('../drive/MyDrive/Colab Notebooks/Estimates/high_conf_test.npy', high_conf_test)

In [ ]:
high_conf_train.shape

(18650, 768)

In [ ]:
high_conf_test.shape

(4663, 768)

In [ ]:
# Load feature encodings
issuekey_vec_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/issuekey_vec_train.npy')
issuekey_vec_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/issuekey_vec_test.npy')

title_vec_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/title_vec_train.npy')
title_vec_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/title_vec_test.npy')

description_vec_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/description_vec_train.npy')
description_vec_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/description_vec_test.npy')

work_comp_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/work_comp_train.npy')
work_comp_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/work_comp_test.npy')

opt_est_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/opt_est_train.npy')
opt_est_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/opt_est_test.npy')

risk_fac_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/risk_fac_train.npy')
risk_fac_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/risk_fac_test.npy')

high_conf_train = np.load('../drive/MyDrive/Colab Notebooks/Estimates/high_conf_train.npy')
high_conf_test = np.load('../drive/MyDrive/Colab Notebooks/Estimates/high_conf_test.npy')

# Label Encoding

In [ ]:
# One hot encoding

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
enc = OneHotEncoder(handle_unknown='ignore')
train_label = train["Final Estimate"].to_numpy().reshape(-1,1)
test_label = test["Final Estimate"].to_numpy().reshape(-1,1)
enc.fit(train_label)

OneHotEncoder(handle_unknown='ignore')

In [ ]:
train_one_hot = enc.transform(train_label).toarray()
test_one_hot = enc.transform(test_label).toarray()
print(train_one_hot.shape, test_one_hot.shape)

(18650, 216) (4663, 216)

In [ ]:
enc.categories_

[array([  4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,
         15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,  25.,
         26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,
         48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,
         59.,  60.,  61.,  62.,  63.,  64.,  66.,  67.,  68.,  69.,  70.,
         71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,
         82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,
         93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102., 103.,
        104., 105., 106., 107., 108., 109., 110., 111., 112., 113., 114.,
        115., 116., 117., 118., 119., 120., 121., 122., 123., 124., 125.,
        126., 127., 128., 129., 130., 131., 132., 133., 134., 135., 137.,
        140., 141., 142., 143., 145., 146., 147., 148., 150., 152., 153.,
        154., 155., 156., 158., 159., 160., 162., 164., 165., 166., 167.,
        169., 172., 174., 175., 176., 177., 178., 179., 180., 181., 182.,
        186., 189., 190., 192., 193., 194., 195., 196., 197., 200., 202.,
        203., 204., 205., 206., 208., 209., 210., 212., 214., 215., 216.,
        217., 219., 220., 221., 222., 224., 226., 228., 229., 230., 231.,
        232., 233., 234., 236., 237., 239., 240., 242., 245., 246., 247.,
        248., 249., 253., 256., 259., 260., 270.])]

## Neural Network

In [ ]:
# Branch-1 Issue key
inp1 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_1")
lay1 = tf.keras.layers.Dense(128, activation='relu')(inp1)
lay1 = tf.keras.layers.Dropout(0.2)(lay1)
lay1 = tf.keras.layers.Dense(128, activation='relu')(lay1)

In [ ]:
# Branch-2 Title
inp2 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_2")
lay2 = tf.keras.layers.Dense(512, activation='relu')(inp2)
lay2 = tf.keras.layers.Dense(128, activation='relu')(lay2)

In [ ]:
# Branch-3 Description
inp3 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_3")
lay3 = tf.keras.layers.Dense(512, activation='relu')(inp3)
lay3 = tf.keras.layers.Dense(128, activation='relu')(lay3)

In [ ]:
# Branch-4 Work Complexity
inp4 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_4")
lay4 = tf.keras.layers.Dense(128, activation='relu')(inp4)
lay4 = tf.keras.layers.Dropout(0.2)(lay4)
lay4 = tf.keras.layers.Dense(128, activation='relu')(lay4)

In [ ]:
# Branch-5 Actual Estimates
inp5 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_5")
lay5 = tf.keras.layers.Dense(128, activation='relu')(inp5)
lay5 = tf.keras.layers.Dropout(0.2)(lay5)
lay5 = tf.keras.layers.Dense(128, activation='relu')(lay5)

In [ ]:
# Branch-6 Risk Factor
inp6 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_6")
lay6 = tf.keras.layers.Dense(128, activation='relu')(inp6)
lay6 = tf.keras.layers.Dropout(0.2)(lay6)
lay6 = tf.keras.layers.Dense(128, activation='relu')(lay6)

In [ ]:
# Branch-7 High Confidence
inp7 = tf.keras.Input(shape=(768,), dtype=tf.int32, name="input_layer_7")
lay7 = tf.keras.layers.Dense(128, activation='relu')(inp7)
lay7 = tf.keras.layers.Dropout(0.2)(lay7)
lay7 = tf.keras.layers.Dense(128, activation='relu')(lay7)

In [ ]:
# Concatenate Branch
out = tf.keras.layers.Concatenate()([lay1, lay2, lay3, lay4, lay5, lay6, lay7])
out = tf.keras.layers.Dense(384, activation='relu')(out)
out = tf.keras.layers.Dense(128, activation='relu')(out)
out = tf.keras.layers.Dense(216, activation='softmax')(out)

In [ ]:
model = tf.keras.models.Model(inputs=[inp1, inp2, inp3, inp4, inp5, inp6, inp7], outputs=out)

## Model Compile

In [ ]:
model.compile(tf.keras.optimizers.Adam(learning_rate=1e-3), loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "model"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to
==================================================================================================
 input_layer_1 (InputLayer)     [(None, 768)]        0           []

 input_layer_4 (InputLayer)     [(None, 768)]        0           []

 input_layer_5 (InputLayer)     [(None, 768)]        0           []

 input_layer_6 (InputLayer)     [(None, 768)]        0           []

 input_layer_7 (InputLayer)     [(None, 768)]        0           []

 dense (Dense)                  (None, 128)          98432       ['input_layer_1[0][0]']

 input_layer_2 (InputLayer)     [(None, 768)]        0           []

 input_layer_3 (InputLayer)     [(None, 768)]        0           []

 dense_6 (Dense)                (None, 128)          98432       ['input_layer_4[0][0]']

 dense_8 (Dense)                (None, 128)          98432       ['input_layer_5[0][0]']

 dense_10 (Dense)               (None, 128)          98432       ['input_layer_6[0][0]']

 dense_12 (Dense)               (None, 128)          98432       ['input_layer_7[0][0]']

 dropout_74 (Dropout)           (None, 128)          0           ['dense[0][0]']

 dense_2 (Dense)                (None, 512)          393728      ['input_layer_2[0][0]']

 dense_4 (Dense)                (None, 512)          393728      ['input_layer_3[0][0]']

 dropout_75 (Dropout)           (None, 128)          0           ['dense_6[0][0]']

 dropout_76 (Dropout)           (None, 128)          0           ['dense_8[0][0]']

 dropout_77 (Dropout)           (None, 128)          0           ['dense_10[0][0]']

 dropout_78 (Dropout)           (None, 128)          0           ['dense_12[0][0]']

 dense_1 (Dense)                (None, 128)          16512       ['dropout_74[0][0]']

 dense_3 (Dense)                (None, 128)          65664       ['dense_2[0][0]']

 dense_5 (Dense)                (None, 128)          65664       ['dense_4[0][0]']

 dense_7 (Dense)                (None, 128)          16512       ['dropout_75[0][0]']

 dense_9 (Dense)                (None, 128)          16512       ['dropout_76[0][0]']

 dense_11 (Dense)               (None, 128)          16512       ['dropout_77[0][0]']

 dense_13 (Dense)               (None, 128)          16512       ['dropout_78[0][0]']

 concatenate (Concatenate)      (None, 896)          0           ['dense_1[0][0]',
                                                                  'dense_3[0][0]',
                                                                  'dense_5[0][0]',
                                                                  'dense_7[0][0]',
                                                                  'dense_9[0][0]',
                                                                  'dense_11[0][0]',
                                                                  'dense_13[0][0]']

 dense_14 (Dense)               (None, 384)          344448      ['concatenate[0][0]']

 dense_15 (Dense)               (None, 128)          49280       ['dense_14[0][0]']

 dense_16 (Dense)               (None, 216)          27864       ['dense_15[0][0]']

==================================================================================================
Total params: 1,915,096
Trainable params: 1,915,096
Non-trainable params: 0
__________________________________________________________________________________________________

In [ ]:
checkpoint = tf.keras.callbacks.ModelCheckpoint('model.h5', monitor='loss', save_best_only=True, verbose=1)

train_sh = model.fit(
    [issuekey_vec_train, title_vec_train, description_vec_train, work_comp_train, opt_est_train, risk_fac_train, high_conf_train], train_one_hot,
    epochs=100,
    callbacks=[checkpoint],
    validation_data=([issuekey_vec_test, title_vec_test, description_vec_test, work_comp_test, opt_est_test, risk_fac_test, high_conf_test], test_one_hot),
    batch_size=32,
    verbose=1
)

Epoch 1/100
579/583 [============================>.] - ETA: 0s - loss: 3.5993 - accuracy: 0.0862
Epoch 1: loss improved from inf to 3.59865, saving model to model.h5
583/583 [==============================] - 13s 9ms/step - loss: 3.5987 - accuracy: 0.0862 - val_loss: 3.4946 - val_accuracy: 0.0856
Epoch 2/100
580/583 [============================>.] - ETA: 0s - loss: 3.4816 - accuracy: 0.0859
Epoch 2: loss improved from 3.59865 to 3.48101, saving model to model.h5
583/583 [==============================] - 7s 11ms/step - loss: 3.4810 - accuracy: 0.0860 - val_loss: 3.4201 - val_accuracy: 0.0926
Epoch 3/100
582/583 [============================>.] - ETA: 0s - loss: 3.4441 - accuracy: 0.0880
Epoch 3: loss improved from 3.48101 to 3.44382, saving model to model.h5
583/583 [==============================] - 5s 8ms/step - loss: 3.4438 - accuracy: 0.0879 - val_loss: 3.4324 - val_accuracy: 0.0946
Epoch 4/100
578/583 [============================>.] - ETA: 0s - loss: 3.4276 - accuracy: 0.0939
Epoch 4: loss improved from 3.44382 to 3.42641, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.4264 - accuracy: 0.0936 - val_loss: 3.3967 - val_accuracy: 0.0901
Epoch 5/100
581/583 [============================>.] - ETA: 0s - loss: 3.4202 - accuracy: 0.0898
Epoch 5: loss improved from 3.42641 to 3.42004, saving model to model.h5
583/583 [==============================] - 13s 22ms/step - loss: 3.4200 - accuracy: 0.0899 - val_loss: 3.4459 - val_accuracy: 0.0860
Epoch 6/100
582/583 [============================>.] - ETA: 0s - loss: 3.4092 - accuracy: 0.0961
Epoch 6: loss improved from 3.42004 to 3.40918, saving model to model.h5
583/583 [==============================] - 9s 15ms/step - loss: 3.4092 - accuracy: 0.0962 - val_loss: 3.4043 - val_accuracy: 0.0733
Epoch 7/100
583/583 [==============================] - ETA: 0s - loss: 3.3981 - accuracy: 0.0923
Epoch 7: loss improved from 3.40918 to 3.39812, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.3981 - accuracy: 0.0923 - val_loss: 3.4068 - val_accuracy: 0.0946
Epoch 8/100
579/583 [============================>.] - ETA: 0s - loss: 3.3950 - accuracy: 0.0986
Epoch 8: loss improved from 3.39812 to 3.39443, saving model to model.h5
583/583 [==============================] - 8s 14ms/step - loss: 3.3944 - accuracy: 0.0985 - val_loss: 3.3764 - val_accuracy: 0.0978
Epoch 9/100
581/583 [============================>.] - ETA: 0s - loss: 3.3909 - accuracy: 0.0960
Epoch 9: loss improved from 3.39443 to 3.38995, saving model to model.h5
583/583 [==============================] - 8s 13ms/step - loss: 3.3899 - accuracy: 0.0964 - val_loss: 3.3596 - val_accuracy: 0.0924
Epoch 10/100
581/583 [============================>.] - ETA: 0s - loss: 3.3859 - accuracy: 0.0940
Epoch 10: loss improved from 3.38995 to 3.38586, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.3859 - accuracy: 0.0939 - val_loss: 3.3625 - val_accuracy: 0.0963
Epoch 11/100
579/583 [============================>.] - ETA: 0s - loss: 3.3770 - accuracy: 0.0968
Epoch 11: loss improved from 3.38586 to 3.37698, saving model to model.h5
583/583 [==============================] - 8s 13ms/step - loss: 3.3770 - accuracy: 0.0972 - val_loss: 3.3820 - val_accuracy: 0.0965
Epoch 12/100
578/583 [============================>.] - ETA: 0s - loss: 3.3757 - accuracy: 0.0940
Epoch 12: loss improved from 3.37698 to 3.37565, saving model to model.h5
583/583 [==============================] - 8s 14ms/step - loss: 3.3756 - accuracy: 0.0938 - val_loss: 3.3668 - val_accuracy: 0.0879
Epoch 13/100
583/583 [==============================] - ETA: 0s - loss: 3.3703 - accuracy: 0.0968
Epoch 13: loss improved from 3.37565 to 3.37027, saving model to model.h5
583/583 [==============================] - 7s 13ms/step - loss: 3.3703 - accuracy: 0.0968 - val_loss: 3.3661 - val_accuracy: 0.0967
Epoch 14/100
583/583 [==============================] - ETA: 0s - loss: 3.3683 - accuracy: 0.0968
Epoch 14: loss improved from 3.37027 to 3.36828, saving model to model.h5
583/583 [==============================] - 7s 12ms/step - loss: 3.3683 - accuracy: 0.0968 - val_loss: 3.3622 - val_accuracy: 0.0959
Epoch 15/100
580/583 [============================>.] - ETA: 0s - loss: 3.3650 - accuracy: 0.0976
Epoch 15: loss improved from 3.36828 to 3.36414, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3641 - accuracy: 0.0977 - val_loss: 3.3610 - val_accuracy: 0.0849
Epoch 16/100
579/583 [============================>.] - ETA: 0s - loss: 3.3590 - accuracy: 0.0969
Epoch 16: loss improved from 3.36414 to 3.35978, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.3598 - accuracy: 0.0968 - val_loss: 3.3654 - val_accuracy: 0.0935
Epoch 17/100
582/583 [============================>.] - ETA: 0s - loss: 3.3566 - accuracy: 0.0978
Epoch 17: loss improved from 3.35978 to 3.35639, saving model to model.h5
583/583 [==============================] - 8s 13ms/step - loss: 3.3564 - accuracy: 0.0979 - val_loss: 3.3649 - val_accuracy: 0.0888
Epoch 18/100
581/583 [============================>.] - ETA: 0s - loss: 3.3513 - accuracy: 0.0972
Epoch 18: loss improved from 3.35639 to 3.35124, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.3512 - accuracy: 0.0974 - val_loss: 3.3800 - val_accuracy: 0.0954
Epoch 19/100
583/583 [==============================] - ETA: 0s - loss: 3.3470 - accuracy: 0.0980
Epoch 19: loss improved from 3.35124 to 3.34695, saving model to model.h5
583/583 [==============================] - 9s 16ms/step - loss: 3.3470 - accuracy: 0.0980 - val_loss: 3.3747 - val_accuracy: 0.0892
Epoch 20/100
581/583 [============================>.] - ETA: 0s - loss: 3.3528 - accuracy: 0.0967
Epoch 20: loss did not improve from 3.34695
583/583 [==============================] - 10s 16ms/step - loss: 3.3537 - accuracy: 0.0965 - val_loss: 3.3770 - val_accuracy: 0.0847
Epoch 21/100
582/583 [============================>.] - ETA: 0s - loss: 3.3527 - accuracy: 0.1001
Epoch 21: loss did not improve from 3.34695
583/583 [==============================] - 8s 14ms/step - loss: 3.3526 - accuracy: 0.1000 - val_loss: 3.3727 - val_accuracy: 0.0905
Epoch 22/100
576/583 [============================>.] - ETA: 0s - loss: 3.3423 - accuracy: 0.0984
Epoch 22: loss improved from 3.34695 to 3.34248, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.3425 - accuracy: 0.0981 - val_loss: 3.4014 - val_accuracy: 0.0999
Epoch 23/100
583/583 [==============================] - ETA: 0s - loss: 3.3348 - accuracy: 0.0985
Epoch 23: loss improved from 3.34248 to 3.33476, saving model to model.h5
583/583 [==============================] - 9s 15ms/step - loss: 3.3348 - accuracy: 0.0985 - val_loss: 3.3823 - val_accuracy: 0.0884
Epoch 24/100
582/583 [============================>.] - ETA: 0s - loss: 3.3284 - accuracy: 0.0979
Epoch 24: loss improved from 3.33476 to 3.32845, saving model to model.h5
583/583 [==============================] - 9s 15ms/step - loss: 3.3285 - accuracy: 0.0979 - val_loss: 3.3823 - val_accuracy: 0.0976
Epoch 25/100
580/583 [============================>.] - ETA: 0s - loss: 3.3301 - accuracy: 0.1004
Epoch 25: loss did not improve from 3.32845
583/583 [==============================] - 6s 10ms/step - loss: 3.3297 - accuracy: 0.1003 - val_loss: 3.3906 - val_accuracy: 0.1004
Epoch 26/100
581/583 [============================>.] - ETA: 0s - loss: 3.3257 - accuracy: 0.1010
Epoch 26: loss improved from 3.32845 to 3.32605, saving model to model.h5
583/583 [==============================] - 6s 11ms/step - loss: 3.3260 - accuracy: 0.1011 - val_loss: 3.3726 - val_accuracy: 0.0888
Epoch 27/100
582/583 [============================>.] - ETA: 0s - loss: 3.3207 - accuracy: 0.1011
Epoch 27: loss improved from 3.32605 to 3.32075, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3207 - accuracy: 0.1011 - val_loss: 3.3842 - val_accuracy: 0.0922
Epoch 28/100
583/583 [==============================] - ETA: 0s - loss: 3.3251 - accuracy: 0.0974
Epoch 28: loss did not improve from 3.32075
583/583 [==============================] - 5s 9ms/step - loss: 3.3251 - accuracy: 0.0974 - val_loss: 3.3772 - val_accuracy: 0.0961
Epoch 29/100
583/583 [==============================] - ETA: 0s - loss: 3.3171 - accuracy: 0.0989
Epoch 29: loss improved from 3.32075 to 3.31713, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.3171 - accuracy: 0.0989 - val_loss: 3.3929 - val_accuracy: 0.1002
Epoch 30/100
577/583 [============================>.] - ETA: 0s - loss: 3.3132 - accuracy: 0.0983
Epoch 30: loss improved from 3.31713 to 3.31381, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3138 - accuracy: 0.0984 - val_loss: 3.3886 - val_accuracy: 0.0989
Epoch 31/100
582/583 [============================>.] - ETA: 0s - loss: 3.3107 - accuracy: 0.1016
Epoch 31: loss improved from 3.31381 to 3.31076, saving model to model.h5
583/583 [==============================] - 6s 11ms/step - loss: 3.3108 - accuracy: 0.1016 - val_loss: 3.3971 - val_accuracy: 0.0991
Epoch 32/100
581/583 [============================>.] - ETA: 0s - loss: 3.3050 - accuracy: 0.1029
Epoch 32: loss improved from 3.31076 to 3.30549, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3055 - accuracy: 0.1030 - val_loss: 3.4115 - val_accuracy: 0.0941
Epoch 33/100
579/583 [============================>.] - ETA: 0s - loss: 3.3040 - accuracy: 0.0987
Epoch 33: loss improved from 3.30549 to 3.30479, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3048 - accuracy: 0.0991 - val_loss: 3.3932 - val_accuracy: 0.0976
Epoch 34/100
582/583 [============================>.] - ETA: 0s - loss: 3.3068 - accuracy: 0.1005
Epoch 34: loss did not improve from 3.30479
583/583 [==============================] - 6s 11ms/step - loss: 3.3070 - accuracy: 0.1003 - val_loss: 3.3929 - val_accuracy: 0.0999
Epoch 35/100
582/583 [============================>.] - ETA: 0s - loss: 3.3091 - accuracy: 0.0990
Epoch 35: loss did not improve from 3.30479
583/583 [==============================] - 5s 9ms/step - loss: 3.3086 - accuracy: 0.0991 - val_loss: 3.4041 - val_accuracy: 0.1012
Epoch 36/100
582/583 [============================>.] - ETA: 0s - loss: 3.3067 - accuracy: 0.0994
Epoch 36: loss did not improve from 3.30479
583/583 [==============================] - 5s 9ms/step - loss: 3.3069 - accuracy: 0.0994 - val_loss: 3.4046 - val_accuracy: 0.0967
Epoch 37/100
576/583 [============================>.] - ETA: 0s - loss: 3.3031 - accuracy: 0.1028
Epoch 37: loss improved from 3.30479 to 3.30314, saving model to model.h5
583/583 [==============================] - 6s 11ms/step - loss: 3.3031 - accuracy: 0.1032 - val_loss: 3.4213 - val_accuracy: 0.0948
Epoch 38/100
581/583 [============================>.] - ETA: 0s - loss: 3.3013 - accuracy: 0.1005
Epoch 38: loss improved from 3.30314 to 3.30181, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.3018 - accuracy: 0.1004 - val_loss: 3.4155 - val_accuracy: 0.1023
Epoch 39/100
581/583 [============================>.] - ETA: 0s - loss: 3.2972 - accuracy: 0.1039
Epoch 39: loss improved from 3.30181 to 3.29767, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.2977 - accuracy: 0.1040 - val_loss: 3.4253 - val_accuracy: 0.0929
Epoch 40/100
577/583 [============================>.] - ETA: 0s - loss: 3.2921 - accuracy: 0.1018
Epoch 40: loss improved from 3.29767 to 3.29233, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.2923 - accuracy: 0.1020 - val_loss: 3.4200 - val_accuracy: 0.0984
Epoch 41/100
577/583 [============================>.] - ETA: 0s - loss: 3.2858 - accuracy: 0.1023
Epoch 41: loss improved from 3.29233 to 3.28534, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.2853 - accuracy: 0.1023 - val_loss: 3.4318 - val_accuracy: 0.0980
Epoch 42/100
580/583 [============================>.] - ETA: 0s - loss: 3.2839 - accuracy: 0.1054
Epoch 42: loss improved from 3.28534 to 3.28319, saving model to model.h5
583/583 [==============================] - 9s 16ms/step - loss: 3.2832 - accuracy: 0.1057 - val_loss: 3.4611 - val_accuracy: 0.1019
Epoch 43/100
583/583 [==============================] - ETA: 0s - loss: 3.2766 - accuracy: 0.1055
Epoch 43: loss improved from 3.28319 to 3.27662, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.2766 - accuracy: 0.1055 - val_loss: 3.4583 - val_accuracy: 0.0954
Epoch 44/100
580/583 [============================>.] - ETA: 0s - loss: 3.2780 - accuracy: 0.1035
Epoch 44: loss did not improve from 3.27662
583/583 [==============================] - 9s 15ms/step - loss: 3.2773 - accuracy: 0.1035 - val_loss: 3.4368 - val_accuracy: 0.0926
Epoch 45/100
582/583 [============================>.] - ETA: 0s - loss: 3.2732 - accuracy: 0.1062
Epoch 45: loss improved from 3.27662 to 3.27340, saving model to model.h5
583/583 [==============================] - 10s 16ms/step - loss: 3.2734 - accuracy: 0.1063 - val_loss: 3.4666 - val_accuracy: 0.0922
Epoch 46/100
580/583 [============================>.] - ETA: 0s - loss: 3.2748 - accuracy: 0.1026
Epoch 46: loss did not improve from 3.27340
583/583 [==============================] - 7s 12ms/step - loss: 3.2738 - accuracy: 0.1029 - val_loss: 3.4719 - val_accuracy: 0.0978
Epoch 47/100
581/583 [============================>.] - ETA: 0s - loss: 3.2723 - accuracy: 0.1031
Epoch 47: loss improved from 3.27340 to 3.27253, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.2725 - accuracy: 0.1031 - val_loss: 3.4790 - val_accuracy: 0.0963
Epoch 48/100
579/583 [============================>.] - ETA: 0s - loss: 3.2641 - accuracy: 0.1071
Epoch 48: loss improved from 3.27253 to 3.26474, saving model to model.h5
583/583 [==============================] - 8s 14ms/step - loss: 3.2647 - accuracy: 0.1070 - val_loss: 3.4571 - val_accuracy: 0.0924
Epoch 49/100
581/583 [============================>.] - ETA: 0s - loss: 3.2735 - accuracy: 0.1043
Epoch 49: loss did not improve from 3.26474
583/583 [==============================] - 10s 18ms/step - loss: 3.2736 - accuracy: 0.1045 - val_loss: 3.4694 - val_accuracy: 0.0989
Epoch 50/100
577/583 [============================>.] - ETA: 0s - loss: 3.2736 - accuracy: 0.1066
Epoch 50: loss did not improve from 3.26474
583/583 [==============================] - 5s 8ms/step - loss: 3.2737 - accuracy: 0.1068 - val_loss: 3.4747 - val_accuracy: 0.0946
Epoch 51/100
579/583 [============================>.] - ETA: 0s - loss: 3.2697 - accuracy: 0.1043
Epoch 51: loss did not improve from 3.26474
583/583 [==============================] - 6s 11ms/step - loss: 3.2690 - accuracy: 0.1043 - val_loss: 3.5338 - val_accuracy: 0.0997
Epoch 52/100
582/583 [============================>.] - ETA: 0s - loss: 3.2693 - accuracy: 0.1040
Epoch 52: loss did not improve from 3.26474
583/583 [==============================] - 5s 9ms/step - loss: 3.2693 - accuracy: 0.1039 - val_loss: 3.4761 - val_accuracy: 0.0948
Epoch 53/100
577/583 [============================>.] - ETA: 0s - loss: 3.2633 - accuracy: 0.1070
Epoch 53: loss improved from 3.26474 to 3.26239, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.2624 - accuracy: 0.1069 - val_loss: 3.4856 - val_accuracy: 0.0884
Epoch 54/100
578/583 [============================>.] - ETA: 0s - loss: 3.2726 - accuracy: 0.1077
Epoch 54: loss did not improve from 3.26239
583/583 [==============================] - 6s 11ms/step - loss: 3.2733 - accuracy: 0.1074 - val_loss: 3.4939 - val_accuracy: 0.0967
Epoch 55/100
583/583 [==============================] - ETA: 0s - loss: 3.2553 - accuracy: 0.1089
Epoch 55: loss improved from 3.26239 to 3.25531, saving model to model.h5
583/583 [==============================] - 5s 9ms/step - loss: 3.2553 - accuracy: 0.1089 - val_loss: 3.5341 - val_accuracy: 0.0948
Epoch 56/100
583/583 [==============================] - ETA: 0s - loss: 3.2541 - accuracy: 0.1072
Epoch 56: loss improved from 3.25531 to 3.25412, saving model to model.h5
583/583 [==============================] - 6s 10ms/step - loss: 3.2541 - accuracy: 0.1072 - val_loss: 3.4933 - val_accuracy: 0.1002
Epoch 57/100
579/583 [============================>.] - ETA: 0s - loss: 3.2476 - accuracy: 0.1093
Epoch 57: loss improved from 3.25412 to 3.24847, saving model to model.h5
583/583 [==============================] - 10s 17ms/step - loss: 3.2485 - accuracy: 0.1093 - val_loss: 3.5620 - val_accuracy: 0.0931
Epoch 58/100
583/583 [==============================] - ETA: 0s - loss: 3.2598 - accuracy: 0.1084
Epoch 58: loss did not improve from 3.24847
583/583 [==============================] - 8s 14ms/step - loss: 3.2598 - accuracy: 0.1084 - val_loss: 3.5079 - val_accuracy: 0.0980
Epoch 59/100
582/583 [============================>.] - ETA: 0s - loss: 3.2436 - accuracy: 0.1096
Epoch 59: loss improved from 3.24847 to 3.24390, saving model to model.h5
583/583 [==============================] - 7s 13ms/step - loss: 3.2439 - accuracy: 0.1095 - val_loss: 3.5249 - val_accuracy: 0.0950
Epoch 60/100
581/583 [============================>.] - ETA: 0s - loss: 3.2469 - accuracy: 0.1084
Epoch 60: loss did not improve from 3.24390
583/583 [==============================] - 10s 17ms/step - loss: 3.2474 - accuracy: 0.1085 - val_loss: 3.5548 - val_accuracy: 0.0916
Epoch 61/100
581/583 [============================>.] - ETA: 0s - loss: 3.2485 - accuracy: 0.1095
Epoch 61: loss did not improve from 3.24390
583/583 [==============================] - 8s 13ms/step - loss: 3.2485 - accuracy: 0.1095 - val_loss: 3.5852 - val_accuracy: 0.0926
Epoch 62/100
583/583 [==============================] - ETA: 0s - loss: 3.2353 - accuracy: 0.1077
Epoch 62: loss improved from 3.24390 to 3.23531, saving model to model.h5
583/583 [==============================] - 6s 11ms/step - loss: 3.2353 - accuracy: 0.1077 - val_loss: 3.5351 - val_accuracy: 0.0971
Epoch 63/100
583/583 [==============================] - ETA: 0s - loss: 3.2416 - accuracy: 0.1088
Epoch 63: loss did not improve from 3.23531
583/583 [==============================] - 5s 9ms/step - loss: 3.2416 - accuracy: 0.1088 - val_loss: 3.5400 - val_accuracy: 0.0956
Epoch 64/100
577/583 [============================>.] - ETA: 0s - loss: 3.2289 - accuracy: 0.1097
Epoch 64: loss improved from 3.23531 to 3.22979, saving model to model.h5
583/583 [==============================] - 5s 8ms/step - loss: 3.2298 - accuracy: 0.1098 - val_loss: 3.5534 - val_accuracy: 0.0965
Epoch 65/100
581/583 [============================>.] - ETA: 0s - loss: 3.2345 - accuracy: 0.1136
Epoch 65: loss did not improve from 3.22979
583/583 [==============================] - 6s 11ms/step - loss: 3.2342 - accuracy: 0.1135 - val_loss: 3.5495 - val_accuracy: 0.0935
Epoch 66/100
577/583 [============================>.] - ETA: 0s - loss: 3.2380 - accuracy: 0.1063
Epoch 66: loss did not improve from 3.22979
583/583 [==============================] - 5s 9ms/step - loss: 3.2366 - accuracy: 0.1065 - val_loss: 3.6104 - val_accuracy: 0.0961
Epoch 67/100
579/583 [============================>.] - ETA: 0s - loss: 3.2335 - accuracy: 0.1095
Epoch 67: loss did not improve from 3.22979
583/583 [==============================] - 5s 9ms/step - loss: 3.2338 - accuracy: 0.1094 - val_loss: 3.6071 - val_accuracy: 0.0929
Epoch 68/100
578/583 [============================>.] - ETA: 0s - loss: 3.2342 - accuracy: 0.1089
Epoch 68: loss did not improve from 3.22979
583/583 [==============================] - 6s 11ms/step - loss: 3.2344 - accuracy: 0.1086 - val_loss: 3.6628 - val_accuracy: 0.0811
Epoch 69/100

In [ ]:
print(train_sh.history)

{'loss': [3.5986545085906982, 3.481005907058716, 3.4438204765319824, 3.426408290863037, 3.4200384616851807, 3.4091830253601074, 3.398124933242798, 3.394432783126831, 3.3899471759796143, 3.3858566284179688, 3.3769752979278564, 3.3756465911865234, 3.370274066925049, 3.368277072906494, 3.3641419410705566, 3.3597819805145264, 3.3563904762268066, 3.351235866546631, 3.346951484680176, 3.3537116050720215, 3.3525543212890625, 3.3424787521362305, 3.3347628116607666, 3.3284525871276855, 3.32965087890625, 3.326046943664551, 3.320748805999756, 3.3251309394836426, 3.317129373550415, 3.3138062953948975, 3.3107619285583496, 3.3054888248443604, 3.304785966873169, 3.307004690170288, 3.308589458465576, 3.3068594932556152, 3.3031387329101562, 3.301809549331665, 3.297668695449829, 3.292330026626587, 3.2853362560272217, 3.283193826675415, 3.276616096496582, 3.2773475646972656, 3.2733957767486572, 3.27380108833313, 3.272526264190674, 3.2647407054901123, 3.2735631465911865, 3.273695468902588, 3.26904296875, 3.269287347793579, 3.2623860836029053, 3.2733302116394043, 3.255311965942383, 3.254115581512451, 3.2484726905822754, 3.259829044342041, 3.243901491165161, 3.24739408493042, 3.2484521865844727, 3.2353076934814453, 3.2415542602539062, 3.2297861576080322, 3.234217643737793, 3.2365915775299072, 3.233842611312866, 3.234375, 3.224785566329956, 3.218925952911377, 3.2160861492156982, 3.2124783992767334, 3.2074644565582275, 3.1972813606262207, 3.2008774280548096, 3.207688808441162, 3.1969690322875977, 3.1977427005767822, 3.1909382343292236, 3.2034671306610107, 3.188103675842285, 3.178774833679199, 3.176966428756714, 3.180295944213867, 3.1793172359466553, 3.164818525314331, 3.183584451675415, 3.1674575805664062, 3.1635184288024902, 3.16127347946167, 3.156689167022705, 3.1707074642181396, 3.156921625137329, 3.1591579914093018, 3.1502108573913574, 3.140523910522461, 3.1352319717407227, 3.140073537826538, 3.1294994354248047, 3.140997886657715], 'accuracy': [0.08616621792316437, 0.08595174551010132, 0.08788203448057175, 0.0935656800866127, 0.0899195745587349, 0.09619303047657013, 0.09227882325649261, 0.09849865734577179, 0.09635388851165771, 0.09394101798534393, 0.09715817868709564, 0.09383378177881241, 0.09678284078836441, 0.09683646261692047, 0.09769436717033386, 0.09683646261692047, 0.09785522520542145, 0.09742627292871475, 0.09801608324050903, 0.0965147465467453, 0.10000000149011612, 0.0980697050690651, 0.09849865734577179, 0.09785522520542145, 0.10032171756029129, 0.10107238590717316, 0.10107238590717316, 0.09737265110015869, 0.09892761707305908, 0.09844504296779633, 0.10160858184099197, 0.10300268232822418, 0.09908847510814667, 0.10032171756029129, 0.09908847510814667, 0.09935656934976578, 0.10321715474128723, 0.10037533193826675, 0.10402144491672516, 0.10198391228914261, 0.10230562835931778, 0.10568364709615707, 0.10546916723251343, 0.1035388708114624, 0.10632707923650742, 0.10289543867111206, 0.10305629670619965, 0.10702412575483322, 0.10445040464401245, 0.10680965334177017, 0.10428954660892487, 0.10386058688163757, 0.1069168895483017, 0.10739946365356445, 0.10890080779790878, 0.10723860561847687, 0.10927613824605942, 0.10836461186408997, 0.10954423248767853, 0.10852546989917755, 0.10949061810970306, 0.10772117972373962, 0.10879356414079666, 0.10981233417987823, 0.11345844715833664, 0.10654155164957047, 0.10938337445259094, 0.10863270610570908, 0.11265415698289871, 0.11184986680746078, 0.11286862939596176, 0.11206434667110443, 0.113243967294693, 0.11651474237442017, 0.1150670275092125, 0.11442359536886215, 0.11431635171175003, 0.11522788554430008, 0.11313673108816147, 0.11383377760648727, 0.11989276111125946, 0.11592493206262589, 0.11592493206262589, 0.11603216826915741, 0.11882037669420242, 0.11865951865911484, 0.11887399107217789, 0.11919570714235306, 0.1212332472205162, 0.12241286784410477, 0.12101876735687256, 0.11882037669420242, 0.12353887408971786, 0.12101876735687256, 0.12337801605463028, 0.12428954243659973, 0.12627345323562622, 0.12230563163757324, 0.12632708251476288, 0.12873995304107666], 'val_loss': [3.4946396350860596, 3.420109987258911, 3.432374954223633, 3.3966593742370605, 3.4459261894226074, 3.4042599201202393, 3.4068105220794678, 3.3763608932495117, 3.3595619201660156, 3.3625242710113525, 3.3819527626037598, 3.366821527481079, 3.366145133972168, 3.3622477054595947, 3.360989809036255, 3.3654487133026123, 3.3649356365203857, 3.3799924850463867, 3.3747148513793945, 3.3769893646240234, 3.3726823329925537, 3.4013640880584717, 3.382338762283325, 3.3823447227478027, 3.3905880451202393, 3.3726212978363037, 3.384204387664795, 3.377223491668701, 3.3929219245910645, 3.3885655403137207, 3.397148370742798, 3.4114997386932373, 3.3932151794433594, 3.392944574356079, 3.404073715209961, 3.4045844078063965, 3.4212610721588135, 3.415510892868042, 3.425318956375122, 3.420031785964966, 3.4318034648895264, 3.4610793590545654, 3.4583399295806885, 3.4367682933807373, 3.466613531112671, 3.471886396408081, 3.479004144668579, 3.457115411758423, 3.469357490539551, 3.474701166152954, 3.533811330795288, 3.476090431213379, 3.4856324195861816, 3.4939112663269043, 3.53413462638855, 3.4933154582977295, 3.5620334148406982, 3.507934093475342, 3.52494740486145, 3.5547566413879395, 3.5852036476135254, 3.535078287124634, 3.5400238037109375, 3.553372383117676, 3.54950213432312, 3.6104116439819336, 3.6071040630340576, 3.662806749343872, 3.5442960262298584, 3.6357524394989014, 3.5693905353546143, 3.6234171390533447, 3.6131699085235596, 3.6371145248413086, 3.6213932037353516, 3.612276077270508, 3.599660873413086, 3.6285459995269775, 3.6829750537872314, 3.679011821746826, 3.627944231033325, 3.787151575088501, 3.71274995803833, 3.737661838531494, 3.7500736713409424, 3.7601282596588135, 3.6556782722473145, 3.701103925704956, 3.7871878147125244, 3.7982773780822754, 3.9441957473754883, 3.7476792335510254, 3.705014944076538, 3.9248175621032715, 3.852710485458374, 3.7899086475372314, 3.8089561462402344, 3.824887990951538, 3.823432445526123, 3.771026134490967], 'val_accuracy': [0.08556722849607468, 0.09264422208070755, 0.09457430988550186, 0.09007076919078827, 0.08599614351987839, 0.07334334403276443, 0.09457430988550186, 0.09779112040996552, 0.0924297645688057, 0.09628994017839432, 0.09650439769029617, 0.0879262313246727, 0.09671884775161743, 0.0958610326051712, 0.0849238708615303, 0.09350203722715378, 0.08878404647111893, 0.09543212503194809, 0.08921295404434204, 0.08470941334962845, 0.09049967676401138, 0.09993566572666168, 0.08835513889789581, 0.09757667034864426, 0.1003645732998848, 0.08878404647111893, 0.09221531450748444, 0.09607549011707306, 0.10015011578798294, 0.0988633930683136, 0.09907785058021545, 0.09414540231227875, 0.09757667034864426, 0.09993566572666168, 0.10122238844633102, 0.09671884775161743, 0.09478875994682312, 0.10229466110467911, 0.09285867214202881, 0.09843448549509048, 0.09800557792186737, 0.101865753531456, 0.09543212503194809, 0.09264422208070755, 0.09221531450748444, 0.09779112040996552, 0.09628994017839432, 0.0924297645688057, 0.0988633930683136, 0.09457430988550186, 0.09972120821475983, 0.09478875994682312, 0.08835513889789581, 0.09671884775161743, 0.09478875994682312, 0.10015011578798294, 0.09307312965393066, 0.09800557792186737, 0.09500321745872498, 0.09157194942235947, 0.09264422208070755, 0.09714775532484055, 0.09564658254384995, 0.09650439769029617, 0.09350203722715378, 0.09607549011707306, 0.09285867214202881, 0.08106369525194168, 0.08856958895921707, 0.08578168600797653, 0.08964186161756516, 0.09071413427591324, 0.08899849653244019, 0.09564658254384995, 0.09264422208070755, 0.0894274041056633, 0.09200085699558258, 0.09543212503194809, 0.09200085699558258, 0.08964186161756516, 0.09371649473905563, 0.08835513889789581, 0.09221531450748444, 0.0943598523736, 0.08706840872764587, 0.08899849653244019, 0.09049967676401138, 0.09178640693426132, 0.09200085699558258, 0.09114304184913635, 0.08685395866632462, 0.09285867214202881, 0.08749731630086899, 0.08728286623954773, 0.08814068138599396, 0.09200085699558258, 0.08663950115442276, 0.09028522670269012, 0.09049967676401138, 0.08578168600797653]}

In [ ]:
model.save('../drive/MyDrive/Colab Notebooks/Estimates/estimates.h5')

In [ ]:
results = model.evaluate([issuekey_vec_test, title_vec_test, description_vec_test, work_comp_test, opt_est_test, risk_fac_test, high_conf_test], test_one_hot, batch_size=16)

292/292 [==============================] - 1s 4ms/step - loss: 3.7710 - accuracy: 0.0858

In [ ]:
predictions = model.predict([issuekey_vec_test, title_vec_test, description_vec_test, work_comp_test, opt_est_test, risk_fac_test, high_conf_test])

146/146 [==============================] - 1s 3ms/step

In [ ]:
print(predictions.shape)
print(test_one_hot.shape)

(4663, 216)
(4663, 216)

In [ ]:
y_actual_label = test["Final Estimate"]
y_pred_label = enc.inverse_transform(predictions)
print(y_actual_label.shape, y_pred_label.shape)

(4663,) (4663, 1)

In [ ]:
test['Predicted Estimate'] = y_pred_label
test.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/Results-updated.csv')

In [ ]:
test.head()

,Unnamed: 0,issuekey,title,description,storypoint,Work Complexity,Optimistic Estimate,Most Likely Estimate,Pessimistic Estimate,Weighted Average,Standard Deviation,Risk Factor,Standard Confidence,High Confidence,Higher Confidence,Highest Confidence,Final Estimate,Predicted Estimate
0,210,MULE-7335,Transformer resolution in TypeBasedTransformer...,TypeBasedTransformerResolver uses registry to ...,5,Medium,8,16,16,14.67,1.33,0.09,14.67,15.37,16.37,17.77,18.0,15.0
1,23125,STUDIO-5331,Remove all references to the non-container Flo...,This involves removing all references to the e...,1,Low,4,6,6,5.67,0.33,0.06,5.67,5.84,6.09,6.44,6.0,9.0
2,4516,TISTUD-7292,"Dashboard: On Windows, Dashboard throws error ...","When Dashboard loads, an error is shown in the...",5,Medium,9,14,14,13.17,0.83,0.06,13.17,13.61,14.23,15.10,15.0,15.0
3,19733,DM-3142,Port HSC optimisations for reading astrometry....,Some astrometry.net catalogs used in productio...,3,Medium,6,10,10,9.33,0.67,0.07,9.33,9.69,10.19,10.89,11.0,9.0
4,4556,TISTUD-7456,"If you publish an Arrow app, the ""Unable to pa...","*Details:* -On Windows,- If you publish an Arr...",5,Medium,8,11,11,10.50,0.50,0.05,10.50,10.76,11.14,11.66,12.0,15.0

In [ ]:
model1 = tf.keras.models.load_model('../drive/MyDrive/Colab Notebooks/Estimates/estimates.h5')

In [ ]:
model1.summary()

In [ ]:
from google.colab import drive
drive.mount('/drive', force_remount=True)

Mounted at /drive

In [ ]:
# For test dataset -> RSpotBot
df_test = pd.read_csv('../drive/MyDrive/Colab Notebooks/Estimates/test_dataset.csv')

df_test["Weighted Average"] = round(((df_test["Optimistic Estimate"] + (4*df_test["Most Likely Estimate"]) + df_test["Pessimistic Estimate"])/6), 2)
df_test["Standard Deviation"] = round(((df_test["Pessimistic Estimate"] - df_test["Optimistic Estimate"])/6), 2)
df_test["Risk Factor"] = round((df_test["Standard Deviation"]/df_test["Weighted Average"]), 2)
df_test["Standard Confidence"] = df_test["Weighted Average"]
df_test["High Confidence"] = round((df_test["Weighted Average"] + (0.53 * df_test["Standard Deviation"])), 2)
df_test["Higher Confidence"] = round((df_test["Weighted Average"] + (1.28 * df_test["Standard Deviation"])), 2)
df_test["Highest Confidence"] = round((df_test["Weighted Average"] + (2.33 * df_test["Standard Deviation"])), 2)
df_test["Final Estimate"] = round(df_test["Highest Confidence"]).astype(int)
df_test["Optimistic Estimate"] = round(df_test["Highest Confidence"]).astype(int)

In [ ]:
df_test.head()

,issuekey,title,description,Work Complexity,Optimistic Estimate,Most Likely Estimate,Pessimistic Estimate,Weighted Average,Standard Deviation,Risk Factor,Standard Confidence,High Confidence,Higher Confidence,Highest Confidence,Final Estimate,Actual Estimate,Predicted Estimate
0,JIRA-1,Collect 5 videos,Manually collect dataset for testing,Low,2,2,2,2.00,0.00,0.00,2.00,2.00,2.00,2.00,2,2,NaN
1,JIRA-2,Test the videos on AWS EC-2 Instance 3,How much our ai engine is taking to give respo...,Low,1,1,1,0.92,0.08,0.09,0.92,0.96,1.02,1.11,1,1,NaN
2,JIRA-3,Research & Brainstorming for improvement,Research and explore ideas to improve time per...,Medium,27,16,32,17.33,4.00,0.23,17.33,19.45,22.45,26.65,27,28,NaN
3,JIRA-4,Optimize the algorithms,Implement the optimized solutions,High,96,80,100,80.00,6.67,0.08,80.00,83.54,88.54,95.54,96,90,NaN
4,JIRA-5,Changes in backend and responses,Make changes in django backend,High,73,60,75,59.17,5.83,0.10,59.17,62.26,66.63,72.75,73,74,NaN

In [ ]:
# Test dataset input encodings

In [ ]:
issuekey_vec_testing = gpt_model.vectors(df_test["issuekey"])

In [ ]:
title_vec_testing = gpt_model.vectors(df_test["title"])

In [ ]:
description_vec_testing = gpt_model.vectors(df_test["description"])

In [ ]:
work_comp_testing = gpt_model.vectors(df_test["Work Complexity"])

In [ ]:
opt_est_testing = gpt_model.vectors(df_test["Optimistic Estimate"])

In [ ]:
risk_fac_testing = gpt_model.vectors(df_test["Risk Factor"])

In [ ]:
high_conf_testing = gpt_model.vectors(df_test["High Confidence"])

In [ ]:
testing_label = df_test["Final Estimate"].to_numpy().reshape(-1,1)

In [ ]:
testing_one_hot = enc.transform(testing_label).toarray()
print(train_one_hot.shape, testing_one_hot.shape)

(18650, 216) (15, 216)

In [ ]:
results = model1.evaluate([issuekey_vec_testing, title_vec_testing, description_vec_testing, work_comp_testing, opt_est_testing, risk_fac_testing, high_conf_testing], testing_one_hot, batch_size=16)

1/1 [==============================] - 0s 30ms/step - loss: 5.2091 - accuracy: 0.0000e+00

In [ ]:
predictions = model1.predict([issuekey_vec_testing, title_vec_testing, description_vec_testing, work_comp_testing, opt_est_testing, risk_fac_testing, high_conf_testing])

1/1 [==============================] - 0s 26ms/step

In [ ]:
print(predictions.shape)
print(test_one_hot.shape)

(15, 216)
(15, 216)

In [ ]:
y_actual_label = df_test["Final Estimate"]
y_pred_label = enc.inverse_transform(predictions)
print(y_actual_label.shape, y_pred_label.shape)

(15,) (15, 1)

In [ ]:
df_test['Predicted Estimate'] = y_pred_label
df_test.to_csv('../drive/MyDrive/Colab Notebooks/Estimates/Results-Test-Dataset.csv')

In [ ]:
df_test.head()

,issuekey,title,description,Work Complexity,Optimistic Estimate,Most Likely Estimate,Pessimistic Estimate,Weighted Average,Standard Deviation,Risk Factor,Standard Confidence,High Confidence,Higher Confidence,Highest Confidence,Final Estimate,Actual Estimate,Predicted Estimate
0,JIRA-1,Collect 5 videos,Manually collect dataset for testing,Low,2,2,2,2.00,0.00,0.00,2.00,2.00,2.00,2.00,2,2,11.0
1,JIRA-2,Test the videos on AWS EC-2 Instance 3,How much our ai engine is taking to give respo...,Low,1,1,1,0.92,0.08,0.09,0.92,0.96,1.02,1.11,1,1,11.0
2,JIRA-3,Research & Brainstorming for improvement,Research and explore ideas to improve time per...,Medium,27,16,32,17.33,4.00,0.23,17.33,19.45,22.45,26.65,27,28,11.0
3,JIRA-4,Optimize the algorithms,Implement the optimized solutions,High,96,80,100,80.00,6.67,0.08,80.00,83.54,88.54,95.54,96,90,11.0
4,JIRA-5,Changes in backend and responses,Make changes in django backend,High,73,60,75,59.17,5.83,0.10,59.17,62.26,66.63,72.75,73,74,11.0